[build]
  command = "npm install"
  publish = "public"
  functions = "functions"

[functions]
  node_bundler = "esbuild"
  included_files = ["data/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
